# NumPy Basics

This notebook covers:
- Introduction to NumPy
- Why NumPy is used
- First NumPy array


### Introduction of NumPy


- Numpy is a Python Library used to perform Mathematical operations.
- It is used to work with arrays.
- It also has functions for working in domain of Linear Algebra and Matrices.

### Why NumPy is used?

- In Python we have List that serves the purpose of NumPy, but they are slow to process.
- NumPy aims to provide an array object that is upto 50x faster than the Python List.
- Arrays are frequently used in Data Science and Data Analysis, where speed and resource are very important.

### First NumPy Array

⭐ Array is the collection of Homogenous Data. It contains the information about Raw data. 
    There are three types of Array :

- 1D Array ->  It is a linear collection of elements arranged in a single row.
- 2D Array ->  It is an array of arrays arranged in rows and columns.
- 3D Array ->  It is a collection of multiple 2-dimensional arrays stacked together.

** Advantages of NumPy array over Python List **

1. Array consumes less memory.
2. Array is fast as compared to python list.
3. It is very convinient to use.


** Importance of NumPy array **

1. It has wide variety of mathematical operations.
2. It supplies an emormous library of high level mathematical functions that operate on these arrays and matrices.
3. Mathematical,logical,shape manipulation,sorting,selecting and many more.


🧱 Creating a First Array

In [7]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8,9,10])                      # example 1
print(arr)

marks = np.array([10,20,30,40])                             # example 2
print(marks)

y = np.array([1,2,3,4,5])                                   # example 3
print(y)


[ 1  2  3  4  5  6  7  8  9 10]
[10 20 30 40]
[1 2 3 4 5]
