# Array Creation

This notebook covers:
   - Zeros array
   - Ones array
   - Empty array
   - Arange array
   - Identity array
   - Linspace array

### Zeros array

A zeros array is a NumPy array in which all elements are initialized to zero.
It is created using the zeros() function and is commonly used to initialize arrays for data processing and computations.

Example:

In [5]:
import numpy as np

arr = np.zeros(5)              
print(arr)

arr1 = np.zeros((3,3))         
print(arr1)

[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### Ones array

A ones array is a NumPy array in which all elements are initialized to one.
It is created using the ones() function and is commonly used to initialize arrays in numerical and data analysis tasks.

Example:

In [6]:
arr2 = np.ones(3)                    
print(arr2)

arr3 = np.ones((3,5))
print(arr3)

[1. 1. 1.]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


### Empty array

An empty array is a NumPy array that is created without initializing its elements.
It is created using the empty() function, and the array contains arbitrary (garbage) values present in memory.

Example:

In [10]:
arr4 = np.empty(2)
print(arr4)

arr5 = np.empty((2,2))
print(arr5)

[0. 0.]
[[2.12199579e-314 1.46205510e-311]
 [5.63234836e-321 3.79442416e-321]]


### Arange array

An arange array is a NumPy array created using the arange() function that generates a sequence of evenly spaced values within a given range.
It is commonly used to create arrays with a specific start, stop, and step value.

Example:

In [11]:
arr6 = np.arange(10)
print(arr6)

arr7 = np.arange(1,10,2)
print(arr7)

[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


### Identity array

An identity array is a square NumPy array in which all the diagonal elements are 1 and all other elements are 0.
It is commonly used in linear algebra and is created using the eye() or identity() function.

Example:

In [14]:
arr8 = np.eye(4)
print(arr8)

arr9 = np.eye(2)
print(arr9)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 0.]
 [0. 1.]]


### Linspace array

A linspace array is a NumPy array created using the linspace() function that generates a specified number of evenly spaced values between a given start and end point.
It is commonly used when the number of required values is known.

Example:

In [17]:
arr10 = np.linspace(1,10,5)
print(arr10)

arr11 = np.linspace(0,30,5)
print(arr11)

[ 1.    3.25  5.5   7.75 10.  ]
[ 0.   7.5 15.  22.5 30. ]
