# Numpy array shape

This notebook covers:
   - Shape()
   - reshape()
   - flatten()
   - ravel()
   - transpose()
   - resize()


### Shape of an array

The shape of an array is the number of elements in each dimension.

### Get the Shape of an Array

NumPy arrays have an attribute called shape that returns a tuple with each index having the number of corresponding elements.

Example:

In [4]:
import numpy as np

arr = np.array([12,3,13,24,45])                    # 1D array
print(arr.shape)

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])       # 2D array
print(arr.shape)                                   

# The example above returns (2, 4), which means that the array has 2 dimensions, where the first dimension has 2 elements and the second has 4.

# Create an array with 5 dimensions:

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)


(5,)
(2, 4)
[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


### Numpy array reshaping

Reshaping means changing the shape of an array.

The shape of an array is the number of elements in each dimension.

By reshaping we can add or remove dimensions or change number of elements in each dimension.

Example:

Reshape From 1-D to 2-D



In [5]:
arr2 = np.array([12,13,14,13,45,67,83,23])
print(arr2)
print()
print(arr2.reshape(4,2))

[12 13 14 13 45 67 83 23]

[[12 13]
 [14 13]
 [45 67]
 [83 23]]


Reshape 1-D to 3-D

In [10]:
arr2 = np.array([12,13,14,13,45,67,83,23,12,13,14,15])
print(arr2)
print()
print(arr2.reshape(2,3,2))

[12 13 14 13 45 67 83 23 12 13 14 15]

[[[12 13]
  [14 13]
  [45 67]]

 [[83 23]
  [12 13]
  [14 15]]]


### Flattening the arrays

Flattening array means converting a multidimensional array into a 1D array.
We can use reshape(-1) to do this.

Example:

In [12]:
arr3 = np.array([12,13,14,13,45,67,83,23,24,54,12,34])
print(arr3)
print()
print(arr3.reshape(3,2,2)) 
print()
print(arr3.reshape(-1)) 

[12 13 14 13 45 67 83 23 24 54 12 34]

[[[12 13]
  [14 13]]

 [[45 67]
  [83 23]]

 [[24 54]
  [12 34]]]

[12 13 14 13 45 67 83 23 24 54 12 34]


### Transpose of array

Transpose in NumPy is an operation that interchanges the rows and columns of an array, producing a new view of the same data with reversed axes.

Example:

In [13]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

transposed = arr.T
print(transposed)

[[1 4]
 [2 5]
 [3 6]]


### Resize of array

Resize in NumPy is a method used to change the shape and size of an array by modifying the original array itself.

Example:

In [14]:
arr = np.array([1, 2, 3, 4])
arr.resize((2, 3))
print(arr)

[[1 2 3]
 [4 0 0]]
