# Join 

This notebook covers:

   - concatenate()
   - vstack()
   - hstack()
   - split()

### Concatenate()

concatenate() is used to join two or more NumPy arrays into a single array along a specified axis.

Syntax:

np.concatenate((array1, array2, ...), axis=0)


Example:

In [10]:
import numpy as np

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])
join = np.concatenate((arr1,arr2))
print(join)

[ 1  2  3  4  5  6  7  8  9 10]
[[1 2 5 6]
 [3 4 7 8]]


In [11]:
# concatenate 2D array (row-wise)
a = np.array([[1, 2],
              [3, 4]])

b = np.array([[5, 6],
              [7, 8]])

result = np.concatenate((a, b), axis=0)
print(result)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [12]:
# concatenate 2D array (column-wise)
result = np.concatenate((a, b), axis=1)
print(result)


[[1 2 5 6]
 [3 4 7 8]]


### vstack()

vstack() is used to stack (join) arrays vertically,
meaning one array is placed below another (row-wise).

Syntax:

np.vstack((array1, array2, ...))

Example:


In [14]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

result = np.vstack((a, b))
print(result)

[[1 2 3]
 [4 5 6]]


In [13]:
# vstack 2D array 
a = np.array([[1, 2],
              [3, 4]])

b = np.array([[5, 6],
              [7, 8]])

result = np.vstack((a, b))
print(result)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


### hstack()

hstack() is used to stack (join) arrays horizontally,
meaning arrays are placed side-by-side (column-wise).

Syntax:

np.hstack((array1, array2, ...))

Example:

In [15]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

result = np.hstack((a, b))
print(result)


[1 2 3 4 5 6]


In [16]:
# hstack 2D array
a = np.array([[1, 2],
              [3, 4]])

b = np.array([[5, 6],
              [7, 8]])

result = np.hstack((a, b))
print(result)

[[1 2 5 6]
 [3 4 7 8]]


# Split

split() is used to divide a NumPy array into multiple smaller sub-arrays.

Syntax:

np.split(array, indices_or_sections)

Example:

In [9]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

result = np.split(arr, 3)
print(result)

[array([1, 2]), array([3, 4]), array([5, 6])]
[array([1, 2]), array([3, 4]), array([5, 6])]
