# Sorting and Searching

This notebook covers:

   - Sort()
   - argsort()
   - where()
   - argmax()
   - argmin()

# SORTING

Sorting is the process of arranging data in a specific order, such as ascending (small → big) or descending (big → small).

Example:

In [3]:
# Ascending order
numbers = [5, 2, 9, 1, 7]

numbers.sort()
print(numbers)


[1, 2, 5, 7, 9]


In [4]:
# Descending order
numbers.sort(reverse=True)
print(numbers)


[9, 7, 5, 2, 1]


### argsort()

argsort() returns the indices that would sort an array.

Example:

In [6]:
a = np.array([40, 10, 30, 20])

result = np.argsort(a)
print(result)


[1 3 2 0]


### where()

where() is used to find indices where a condition is true, or to choose values based on a condition

Example:

In [7]:
a = np.array([2, 6, 4, 9, 1])

result = np.where(a > 5)
print(result)


(array([1, 3]),)


In [9]:
# Replace values using condition
a = np.array([2, 6, 4, 9, 1])

result = np.where(a > 5, 1, 0)
print(result)


[0 1 0 1 0]


# SEARCHING

Searching is the process of finding a specific element in a collection of data.

Example:

In [10]:
numbers = [10, 20, 30, 40, 50]

if 30 in numbers:
    print("Element found")
else:
    print("Element not found")


Element found


In [12]:
# Searching using loop
key = 40
found = False

for num in numbers:
    if num == key:
        found = True
        break

print(found)


True
