# Numpy Basics

Question 1 -: Create a NumPy array from a Python list.

Solution:

In [34]:
import numpy as np

py_list = [1,2,3,4,5,6,7,8,9,10]

arr = np.array(py_list)
print(arr)
print(type(arr))

[ 1  2  3  4  5  6  7  8  9 10]
<class 'numpy.ndarray'>


Question 2 -: Create a 1D array with numbers from 1 to 10.

Solution:

In [7]:
# creating array using arange function
arr_create = np.arange(1,11)

print(arr_create)

[ 1  2  3  4  5  6  7  8  9 10]


Question 3 -: Check the type of a NumPy array.

Solution:

In [8]:
arr_type_check = np.array([1,12,13,14,15])

print(type(arr_type_check))

<class 'numpy.ndarray'>


Question 4 -: Find the shape and dimension of an array.

Solution:


In [9]:
arr_shape = np.array([1,12,13,14,15])
print(arr_shape.shape)

arr_dim = np.array([12,14,15,2,3])
print(arr_dim.ndim)

(5,)
1


Question 5 -: Difference between Python list and NumPy array.

Solution:

python list are slower in performance and are stored in non-contiguous memory location whereas, numpy array are faster for numerical operation and are stored in contiguous memory location.

# Array Creation Methods

Question 6 -: Create an array using zeros(), ones(), and full().

Solution

In [33]:
# creating array using zeros()

zeros_arr = np.zeros(5)                     # 1D array
zeros_arr1 = np.zeros((2,3))                # 2D array

print(zeros_arr)
print(zeros_arr1)

[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]


In [31]:
# creating array using ones()

ones_arr = np.ones(3)              # 1D array
ones_arr1 = np.ones((3,3))         # 2D array

print(ones_arr)
print(ones_arr1)


[1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [32]:
# creating array using full()

full_arr = np.full(5,3)           # 1D array
full_arr1 = np.full((4,3),10)     # 2D array

print(full_arr)
print(full_arr1)

[3 3 3 3 3]
[[10 10 10]
 [10 10 10]
 [10 10 10]
 [10 10 10]]


Question 7 -: Create an identity matrix.

Solution

In [17]:
# creating identity matrix using eye function

identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Question 8 -: Generate numbers using arange() and linspace().

Solution:

In [30]:
# creating array using arange function

arange_arr = np.arange(1,10)
arange_arr1 = np.arange(10,21)

print(arange_arr)
print(arange_arr1)


[1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19 20]


In [24]:
# creating array using linspace function

lin_arr = np.linspace(1,10,4)
lin_arr1 = np.linspace(10,30,5)

print(lin_arr)
print(lin_arr1)

[ 1.  4.  7. 10.]
[10. 15. 20. 25. 30.]


Question 9 -: Create a random array of size (3×3).

Solution:

In [29]:
# creating array using rand() function

random_arr = np.random.rand(3,3)
print(random_arr)

[[0.93461992 0.93780411 0.61605984]
 [0.69068843 0.55270948 0.02353278]
 [0.80545901 0.51180485 0.5575409 ]]


# Indexing and slicing

Question 10: Access the 3rd element from an array.

Solution:

In [4]:
import numpy as np

arr = np.array([2,3,12,14,15])
print(arr[3])

14


Question 11: Slice elements from index 2 to 6.

Solution:

In [6]:
arr_slice = np.array([1,2,3,4,5,12,13,45])
print(arr_slice[2:6])

[ 3  4  5 12]


Question 12: Extract a sub-matrix from a 2D array.

Solution:

In [16]:
arr_ind = np.array([[12,34,56],[34,12,34]])
print(arr_ind[1:3,1:3])


[[12 34]]


Question 13: Change a specific element using indexing.

Solution:

In [21]:
arr = np.array([12,1,2,3,45,9])
arr[0] = 40
print(arr)

[40  1  2  3 45  9]


Question 14: Add two NumPy arrays.

Solution:

In [25]:
a = np.array([1,2,13,12,4])
b = np.array([4,5,32,12,6])
print(a + b)

# we can add them by using add function too.
print(np.add(a,b))

[ 5  7 45 24 10]
[ 5  7 45 24 10]


Question 15: Multiply all elements by 5

Solution:

In [32]:
c = np.array([12,1,4,5,6])
print(np.multiply(c,5))

[60  5 20 25 30]


Question 16: Perform element-wise multiplication.

Solution:

In [33]:
d = np.array([1,2,3,4,5])
e = np.array([12,3,4,5,6])
print(d*e)

[12  6 12 20 30]


Question 17: Find maximum and minimum values.

Solution:

In [5]:
import numpy as np

arr_a = np.array([12,13,1,14,15])
arr_b = np.array([3,4,5,6,7])

# for maximum
print(np.max(arr_a))

# for minumum
print(np.min(arr_b))

15
3


Question 18: Create an array and find its mean.

Solution:

In [6]:
arr = np.array([12,13,2,4,5])
print(np.mean(arr))

7.2


Question 19: Replace all values greater than 50 with 0.

Solution:

In [13]:
arr1 = np.array([12,13,45,66,77,32,89,90])
arr1[arr1 > 50] = 0
print(arr1)

[12 13 45  0  0 32  0  0]


Question 20: Reverse a numpy array.

Solution

In [17]:
arr_rev = np.array([12,23,45,67,3])
print(arr_rev[::-1])

[ 3 67 45 23 12]


Question 21: Count total elements.

Solution:


In [19]:
arr_count = np.array([12,13,24,54,67])
print(np.size(arr_count))

5


Question 22: Find mean, median, and standard deviation.

Solution:

In [2]:
import numpy as np

# Mean 
arr_mean = np.array([12,13,23,45,67])
print(np.mean(arr_mean))

32.0


In [3]:
# Median

arr_med = np.array([12,23,14,8,9])
print(np.median(arr_med))

12.0


In [5]:
# Standard deviation

arr_st = np.array([1,3,4,67,8])
print(np.std(arr_st))

25.30296425322535


Question 23: Use sum() along rows and columns.

Solution:

In [18]:
# Using rows

arr_row = np.array([[12,34,56],
                    [12,4,23]])
print(np.sum(arr_row,axis=1))

[102  39]


In [19]:
# Using columns

arr_col = np.array([[1,3,4],
                    [3,5,6]])
print(np.sum(arr_col,axis=0))            

[ 4  8 10]


Question 24: Apply sqrt() and log() on array.

Solution:

In [22]:
# Sqrt()

arr_sqrt = np.array([4,9,16,25,36])
print(np.sqrt(arr_sqrt))

[2. 3. 4. 5. 6.]


In [23]:
# log()

arr_log = np.array([4,3,6,5,36])
print(np.log(arr_log))

[1.38629436 1.09861229 1.79175947 1.60943791 3.58351894]


Question 25: Round array values to 2 decimals.

Solution:

In [26]:
arr_deci = np.array([1.7878, 23.45666, 2.4567])
print(np.round(arr_deci,2))

[ 1.79 23.46  2.46]
