Question 26: Find value greator than 30.

Solution:

In [5]:
import numpy as np

arr_val = np.array([12,3,4,56,78,43,5])
result = arr_val[arr_val>30]
print(result)

[56 78 43]


Question 27: Count even numbers in an array.

Solutions:

In [12]:
arr_count = np.array([1,23,12,4,6,5,78,32,55])
result = np.sum(arr_count % 2 == 0)
print(result)

5


Question 28: Replace negative numbers with zero.

Solution:

In [16]:
arr_replace = np.array([12,3,4,-7,-3,23,-5,34])
arr_replace[arr_replace < 0] = 0
print(arr_replace)

[12  3  4  0  0 23  0 34]


Question 29: Extract values between 20 and 60.

Solution:

In [23]:
arr = np.array([12,34,56,60,78,43,7,34,46,25])
result = arr[(arr>20) & (arr<60)]
print(result)

[34 56 43 34 46 25]
