Question 30: Convert 1D array to 2D.

Solution:

In [7]:
import numpy as np

arr = np.array([12,34,5,21,3,5])
arr_2d = arr.reshape(2,3)
print(arr_2d)


[[12 34  5]
 [21  3  5]]


Question 31: Convert 2D array into 1D.

Solution:

In [11]:
arr_2d = np.array([[12,3,4,5]])
print(arr_2d.flatten())

[12  3  4  5]


Question 32: Convert matrix into column vector.

Solution:

In [12]:
matrix = np.array([[12,34,2,5,6],
                   [1,7,5,4,2]])
new_matrix = matrix.reshape(-1,1)
print(new_matrix)

[[12]
 [34]
 [ 2]
 [ 5]
 [ 6]
 [ 1]
 [ 7]
 [ 5]
 [ 4]
 [ 2]]


Question 33: Convert matrix into row vector.

Solution:

In [13]:
matrix_2 = np.array([[12,3,2,4],
                     [3,4,5,6]])
new_matrix_2 = matrix_2.reshape(1,-1)
print(new_matrix_2)

[[12  3  2  4  3  4  5  6]]
