Question 34: Sort an array.

Solution:

In [2]:
import numpy as np

arr_1 = np.array([12,3,5,43,67])
sort = np.sort(arr_1)
print(sort)

[ 3  5 12 43 67]


Question 35: Sort a 2D array row-wise.

Solution:

In [9]:
arr_2D = np.array([[12,3,45,3,4],
                   [12,34,6,21,6]])
sort_2D = np.sort(arr_2D)
print(sort_2D)


[[ 3  3  4 12 45]
 [ 6  6 12 21 34]]


Question 36: Find index of max value.

Solution:

In [11]:
arr_max = np.array([12,3,4,21,4,5])
print(np.argmax(arr_max))

3


Question 37: Use where() condition.

Solution:

In [12]:
array = np.array([12,3,45,32,6])
print(np.where(array == 45))


(array([2]),)
